# Generated by Django 5.1.2 on 2024-11-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0014_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(default='Non-professional', max_length=100),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
