# Generated by Django 5.1.2 on 2024-11-09 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0017_skilloption'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SkillOption',
        ),
    ]
