# Generated by Django 5.1.2 on 2024-11-10 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0020_publicprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='skill_images/'),
        ),
    ]
